databases:
  - name: pms-postgres
    databaseName: pms_db
    user: pms_user
    plan: free

services:
  # 1. Java Spring Boot Backend Service (Free Tier)
  - type: web
    name: pms-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: pms-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pms-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: pms-postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: pms-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pms-postgres
          property: password
      - key: SERVER_PORT
        value: 8081
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: premanandabspp@gmail.com
      - key: MAIL_FROM
        value: premanandabspp@gmail.com
        

  # 2. Vite React Frontend Service (Free Tier)
  - type: web
    name: pms-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        value: https://pms-backend-8wx3.onrender.com
